name: tensorflow-gpu
version: git
summary: Machine Learning.
description: | An open-source software library used for machine learning models.
 

confinement: devmode
base: core18

architectures:
  - build-on: i386
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

parts:
  tensorflow-gpu:
    plugin: 
    source-type: 
    source: 
    
    build-packages:
      
    stage-packages:
      

apps:
 tensorflow-gpu:
    command: bin/tensorflow-gpu
    plugs:
      - docker
      - home
      - network
      - removable-media
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/lib/
	  $SNAPCRAFT_ARCH_TRIPLET"
      "DISABLE_WAYLAND": "1"
